#!/usr/bin/env bash
# The script displays "To infinity and beyond" indefinitely and "I am invincible!!!" when recieving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
